AWSTemplateFormatVersion: '2010-09-09'
Description: Creaci贸n de T贸picos SNS
Parameters:
  Project:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
Resources:
  TopicPipelineManualAproval:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: Aprobaci贸n Manual de Pipeline
      Subscription: 
        - Endpoint: raul.vergara@pragma.com.co
          Protocol: email
      TopicName: !Sub ${Project}-SNS-ManualApproval
Outputs:
  TopicForPipelineManualAprovalArn:
    Description: Arn del T贸pico para CodePipeline
    Value: !Ref TopicPipelineManualAproval
    Export:
      Name:
        !Sub ${Project}-TopicPipelineManualAproval
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto