---
AWSTemplateFormatVersion: 2010-09-09
Description: Setup AWS workstream-specific resources for CI/CD cwe codepipeline - By Pragma -> DevOps
Parameters:
  ArtifactS3Bucket:
    Description: Bucket S3 para artefactos de codepipeline
    Type: String
    Default: codepipeline-us-east-1-225379705428
  BranchName:
    Description: Nombre de la rama a desplegar
    Type: String
    AllowedValues:
      - "develop"
      - "qa"
      - "master"
    Default: develop
  CodeBuildRole:
    Description: Nombre del rol de codebuild
    Type: String
    Default: kiire-iam-role-codebuild-back
  EcsClusterName:
    Description: Nombre del cluster ECS
    Type: String
    Default: kiire-ecs-cluster-dev
  EcsServiceName:
    Description: Nombre del servicio en ECS
    Type: String
    Default: kiire-ecs-archetype
  PipelineRole:
    Description: Nombre del rol de codepipeline
    Type: String
    Default: kiire-iam-role-codepipeline-back
  ProjectName:
    Description: Nombre del proyecto a desplegar
    Type: String
    Default: archetype

Resources:
  AmazonCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '-', [ 'kiire-back-cwe-role', !Ref 'ProjectName', !Ref 'BranchName' ] ]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: !Join [ '-', [ 'kiire-back-cwe-pipeline-execution', !Ref 'ProjectName', !Ref 'BranchName' ] ]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref CodePipeline ] ]
  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', 'kiire-back-' ,!Ref 'ProjectName'] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref 'BranchName'
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', !Ref CodePipeline ] ]
          RoleArn: !GetAtt AmazonCloudWatchEventRole.Arn
          Id: !Join [ '', [ 'kiire-back-' ,!Ref 'ProjectName', '-', !Ref 'BranchName', '-cwe-cp' ] ]
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      RoleArn: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':', 'role/service-role/', !Ref 'PipelineRole' ] ]
      ArtifactStore:
        Location: !Ref ArtifactS3Bucket
        Type: S3
      Name: !Join [ '-', [ 'kiire-back', !Ref 'ProjectName', !Ref 'BranchName', 'cp' ] ]
      Stages:
      - Name: Source
        Actions:
        - ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeCommit
            Version: '1'
          Configuration:
            BranchName: !Ref 'BranchName'
            OutputArtifactFormat: CODE_ZIP
            PollForSourceChanges: false
            RepositoryName: !Join [ '-', [ 'kiire-back', !Ref 'ProjectName'] ]
          InputArtifacts: []
          Name: Source
          Namespace: SourceVariables
          OutputArtifacts:
          - Name: SourceArtifact
          Region: us-east-1
          RunOrder: 1
      - Name: Build
        Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Configuration:
            ProjectName: !Join [ '-', [ 'kiire-back', !Ref 'ProjectName', 'cb'] ]
          InputArtifacts:
          - Name: SourceArtifact
          Name: Build
          Namespace: BuildVariables
          OutputArtifacts:
          - Name: BuildArtifact
          Region: us-east-1
          RunOrder: 1
      - Name: Deploy
        Actions:
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: ECS
            Version: '1'
          Configuration:
            ClusterName: !Ref 'EcsClusterName'
            FileName: imagedefinitions.json
            ServiceName: !Ref 'EcsServiceName'
          InputArtifacts:
          - Name: BuildArtifact
          Name: Deploy
          OutputArtifacts: []
          Region: us-east-1
          RunOrder: 1
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Join [ '-', [ 'kiire-back', !Ref 'ProjectName', 'cb'] ]
      ServiceRole: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':', 'role/service-role/', !Ref 'CodeBuildRole' ] ]
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: false
      Cache:
        Type: NO_CACHE
      Description: !Sub Compilacion de microservicio de ${ProjectName} de Kiire
      # EncryptionKey: !Join [ '', [ 'arn:aws:kms:', !Ref 'AWS::Region', !Ref 'AWS::AccountId', ':', 'alias/aws/s3'] ]
      EncryptionKey: 'alias/aws/s3'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: SOURCE_BRANCH
            Type: PLAINTEXT
            Value: "#{SourceVariables.BranchName}"
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: "#{SourceVariables.BranchName}"
        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Source:
        BuildSpec: pipeline/buildspec.yml
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        InsecureSsl: false
        Location: !Join [ '', [ 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/', 'kiire-back-' ,!Ref 'ProjectName'] ]
        Type: CODECOMMIT
      SourceVersion: !Join [ '', [ 'refs/heads/' ,!Ref 'BranchName'] ]
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          EncryptionDisabled: false
          Status: DISABLED
      QueuedTimeoutInMinutes: 480
      SecondaryArtifacts: []
      SecondarySourceVersions: []
      SecondarySources: []
      TimeoutInMinutes: 30
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Ref ComputeType
        Image: !Ref Image
        Type: LINUX_CONTAINER
      Name: !Sub "${ProjectName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: pipeline/buildspec.yml
        Type: CODEPIPELINE