AWSTemplateFormatVersion: 2010-09-09
Description: Lambda para desplegar recursos en AWS
Parameters:
  KeyFileLambdaDeployment:
    Type: String
    Description: Nombre del archivo con el deployment de la lambda para generar versión
    Default: LambdaDeployment201625.zip
  Project:
    Type: String
    Description: Nombre del Proyecto
    Default: ito
  Environment:
    Type: String
    Description: Nombre del Ambiente
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
Resources:
  DeploymentLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role:
        Fn::ImportValue:
          !Sub "${Project}-${Environment}-RoleCustomResourceLambdaArn"
      Handler: index.handler
      Runtime: nodejs16.x
      Description: Lambda para crear recursos de AWS
      FunctionName: !Sub ${Project}-${Environment}-lambda-deployment-custom-resources
      Code:
        S3Bucket:
          Fn::ImportValue:
            !Sub ${Project}-${AWS::AccountId}-BucketDeploymentsName
        S3Key: !Ref KeyFileLambdaDeployment
Outputs:
  DeploymentLambdaArn:
    Description: Arn de la Lambda para crear recursos
    Value: !GetAtt DeploymentLambda.Arn
    Export:
      Name: !Sub ${Project}-${Environment}-DeploymentLambdaArn
