AWSTemplateFormatVersion: 2010-09-09
Description: Api gateway
Parameters:
  ParentId:
    Type: String
  RestApiId:
    Type: String
  PathPart:
    Type: String
  HttpMethod:
    Type: String
    Default: GET
    AllowedValues:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD
      - OPTIONS
      - ANY
  ConnectionType:
    Type: String
    Default: VPC_LINK
    AllowedValues:
      - VPC_LINK
      - INTERNET
  VpcLinkConnectionId:
    Type: String
  TypeIntegration:
    Type: String
    Default: HTTP_PROXY
    AllowedValues:
      - HTTP
      - HTTP_PROXY
  ValidateRequestBody:
    Type: String
    AllowedValues:
      - true
      - false
  ValidateRequestParameters:
    Type: String
    AllowedValues:
      - true
      - false
Conditions:
  isConectionPrivate: !Equals [ VPC_LINK, !Ref ConnectionType ]

Resources:

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ParentId
      RestApiId: !Ref RestApiId
      PathPart: !Ref PathPart
  
  RequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref RestApiId
      ValidateRequestBody: !Ref ValidateRequestBody
      ValidateRequestParameters: !Ref ValidateRequestParameters

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RequestValidatorId: !Ref RequestValidator
      HttpMethod: !Ref HttpMethod
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref RestApiId
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        Type: !Ref TypeIntegration
        IntegrationHttpMethod: !Ref HttpMethod
        Uri: http://ito-dev-network-4cc45d4c275143f9.elb.us-east-1.amazonaws.com:9000/{proxy}
        ConnectionType: !Ref ConnectionType
        ConnectionId: !If [ isConectionPrivate, !Ref VpcLinkConnectionId, !Ref AWS::NoValue ]
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
        # RequestTemplates:
        #   application/json: |
        #     {
        #       "statusCode": 200,
        #       "body": $input.json('$')
        #     }
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: $input.json('$')
      MethodResponses:
        - StatusCode: 200

Outputs:
  ApiGatewayResource:
    Value: !Ref ApiGatewayResource