AWSTemplateFormatVersion: 2010-09-09
Description: Api gateway
Parameters:
  DeploymentTime:
    Type: String
    Default: 0
  AllowLogs:
    Type: String
    Default: 0
    AllowedValues:
      - 1
      - 0
  Environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - pdn
    Default: dev
  Project:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
  ApiName:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
  S3KeyFileLambdaAuthorizer:
    Type: String
    Default: lambda-authorizer-package202956.zip
  S3KeyFileLambdaBackEnd:
    Type: String
    Default: lambda-back-package202956.zip
  CertificateKey:
    Type: String
    Default: "NO"
    AllowedPattern: (NO)|((\w|\d){8})\-((\w|\d){4})\-((\w|\d){4})\-((\w|\d){4})\-((\w|\d){12})
  DomainBack:
    Type: String
    Default: "NO"
    AllowedPattern: (NO)|((^api)\.(\w*\d*)((.pragma.com.co)))
  DummyAuthorizer:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DefaultEndpoint:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  TracingXRay:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  DummyIP:
    Type: String
    Default: '1.1.1.1'
    AllowedPattern: ^(((\d){1,3})\.((\d){1,3})\.((\d){1,3})\.((\d){1,3}))$
Conditions:
  EnableLogs: !Equals [ 1, !Ref AllowLogs ]
  SinDominio: !Equals [ "NO", !Ref DomainBack ]
  SinCertificado: !Equals [ "NO", !Ref CertificateKey ]
  SinCertificadoNiDominio: !Or [ Condition: SinDominio, Condition: SinCertificado ]
  SinCustomDomain: !Not [ Condition: SinCertificadoNiDominio ]
  isDummyAuth: !Equals [ true, !Ref DummyAuthorizer ]
  EnableXRay: !Equals [ true, !Ref TracingXRay ]
Resources:
  
  LambdaAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns: !If [ EnableLogs, arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole, !Ref AWS::NoValue ]
      RoleName: !Sub ${Project}-${Environment}-role-lambda-authorizer
  LambdaAuthorizer:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub ${Project}-${AWS::AccountId}-BucketDeploymentsName
        S3Key: !Ref S3KeyFileLambdaAuthorizer
      Description: Lambda prueba deploy
      FunctionName: !Sub ${Project}-${Environment}-lambda-authorizer
      Handler: !If [ isDummyAuth, index.lambda_handler_dummy, index.handler ]
      MemorySize: 128
      Role: !GetAtt LambdaAuthorizerRole.Arn
      Runtime: python3.9
      Timeout: 128
  LambdaAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaAuthorizer
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*
  LambdaBackendRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !If [ EnableLogs, arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole, !Ref AWS::NoValue ]
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      RoleName: !Sub ${Project}-${Environment}-role-lambda-backend
  LambdaBackend:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub ${Project}-${AWS::AccountId}-BucketDeploymentsName
        S3Key: !Ref S3KeyFileLambdaBackEnd
      Description: Lambda prueba deploy
      FunctionName: !Sub ${Project}-${Environment}-lambda-backend
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaBackendRole.Arn
      Runtime: nodejs16.x
      Timeout: 128
      TracingConfig:
          Mode: !If [ EnableXRay, Active, PassThrough ]
  LambdaBackendPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaBackend
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: !Ref ApiName
      Name: !Sub ${Project}-${Environment}-${ApiName}
      EndpointConfiguration:
        Types:
          - REGIONAL
      ApiKeySourceType: HEADER
      Body:
        openapi: "3.0.1"
        x-amazon-apigateway-endpoint-configuration:
          disableExecuteApiEndpoint: !Ref DefaultEndpoint
        paths:
          /api-retiros:
            get:
              parameters:
              - name: "Authorization"
                in: "header"
                required: true
                schema:
                  type: "string"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              security:
              - AuthorizerLamba: []
              x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
              \ and headers"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub:
                    - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ArnLambda}/invocations
                    - ArnLambda: !GetAtt LambdaBackend.Arn
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
            post:
              parameters:
              - name: "Authorization"
                in: "header"
                required: true
                schema:
                  type: "string"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              security:
              - AuthorizerLamba: []
              x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
              \ and headers"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub:
                    - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ArnLambda}/invocations
                    - ArnLambda: !GetAtt LambdaBackend.Arn
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
            options:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                    Access-Control-Allow-Methods:
                      schema:
                        type: "string"
                    Access-Control-Allow-Headers:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-integration:
                type: "mock"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
          /api-retiros-public:
            get:
              parameters:
              - name: "limit"
                in: "query"
                required: true
              - name: "page"
                in: "query"
                required: true
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
              \ and headers"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub:
                    - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ArnLambda}/invocations
                    - ArnLambda: !GetAtt LambdaBackend.Arn
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
            options:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                    Access-Control-Allow-Methods:
                      schema:
                        type: "string"
                    Access-Control-Allow-Headers:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-integration:
                type: "mock"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
          /api-dummy:
            get:
              produces:
              - application/json
              responses:
                "200":
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                httpMethod: GET
                uri: !Sub http://${DummyIP}:9000/api/dummy
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: when_no_match
                type: http
        components:
          schemas:
            Empty:
              title: "Empty Schema"
              type: "object"
          securitySchemes:
            api_key:
              type: "apiKey"
              name: "x-api-key"
              in: "header"
            AuthorizerLamba:
              type: "apiKey"
              name: "Authorization"
              in: "header"
              x-amazon-apigateway-authtype: "custom"
              x-amazon-apigateway-authorizer:
                authorizerUri:
                  Fn::Sub:
                    - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ArnLambda}/invocations
                    - ArnLambda: !GetAtt LambdaAuthorizer.Arn
                authorizerResultTtlInSeconds: 300
                identitySource: "method.request.header.Authorization"
                type: "request"
        x-amazon-apigateway-gateway-responses:
          DEFAULT_4XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          DEFAULT_5XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        x-amazon-apigateway-request-validators:
          Validate body, query string parameters, and headers:
            validateRequestParameters: true
            validateRequestBody: true
  Deployment:
    Type: Custom::ApiDeployment
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub ${Project}-${Environment}-DeploymentLambdaArn
      restApiId: !Ref ApiGateway
      description: !Sub Deployment in ${DeploymentTime}
      DeploymentTime: !Ref DeploymentTime
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref Deployment
      RestApiId: !Ref ApiGateway
      Description: Default Stage
      StageName: !Ref Environment
      Variables:
        host: test
      TracingEnabled: !Ref TracingXRay
      # AccessLogSetting:
      #   DestinationArn:
      #     Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/ProcessRefound:*
      #   Format: '{ "requestId": "$context.requestId", "DomainName": "$context.domainName", "SourceIp": "$context.identity.sourceIp", "APIId": "$context.apiId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "protocol": "$context.protocol", "responseLength": "$context.responseLength", "Stage": "$context.stage", "errormessage": "$context.error.message", "errormessageString": "$context.error.messageString", "responseType": "$context.error.responseType", "identitycaller": "$context.identity.caller", "integrationerror": "$context.integration.error", "integrationintegrationStatus": "$context.integration.integrationStatus", "integrationErrorMessage": "$context.integrationErrorMessage", "integrationrequestId": "$context.integration.requestId", "EndpointRequestId": "$context.awsEndpointRequestId", "awsEndpointRequestId2": "$context.awsEndpointRequestId2", "clientCertserialNumber": "$context.identity.clientCert.serialNumber", "clientCertvaliditynotBefore": "$context.identity.clientCert.validity.notBefore", "clientCertvaliditynotAfter": "$context.identity.clientCert.validity.notAfter", "requestOverrideheadername": "$context.requestOverride.header.header_name", "requestOverridepathname": "$context.requestOverride.path.path_name", "responseOverrideheadername": "$context.responseOverride.header.header_name", "responseOverridestatus": "$context.responseOverride.status"}'
      # MethodSettings:
      #   - DataTraceEnabled: true
      #     HttpMethod: '*'
      #     LoggingLevel: INFO
      #     MetricsEnabled: true
      #     ResourcePath: /*
      #     ThrottlingBurstLimit: 5000
      #     ThrottlingRateLimit: 10000

  APICustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: SinCustomDomain
    Properties:
      RegionalCertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${CertificateKey}
      DomainName: !Ref DomainBack
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  MappingAPI:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: SinCustomDomain
    Properties: 
      DomainName: !Ref APICustomDomainName
      RestApiId: !Ref ApiGateway
      Stage: !Ref Environment

Outputs:
  ApiGateway:
    Description: ApiGateway id generated
    Value: !Ref ApiGateway
    Export:
      Name: !Sub ${Project}-${Environment}-ApiGatewayId
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
          - Environment
      - Label: 
          default: Datos del API Gateway
        Parameters: 
          - ApiName
          - DefaultEndpoint
          - DomainBack
          - CertificateKey
          - TracingXRay
          - DeploymentTime
      - Label: 
          default: Datos del Funciones Lambda
        Parameters: 
          - AllowLogs
          - S3KeyFileLambdaAuthorizer
          - S3KeyFileLambdaBackEnd
          - DummyAuthorizer
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto
      Environment: 
        default: Nombre del Ambiente
      DeploymentTime: 
        default: Dato para generar un nuevo deployment del API
      AllowLogs: 
        default: Habilitar permisos para generar logs de las funciones Lambdas
      S3KeyFileLambdaAuthorizer: 
        default: Key del archivo con el codigo de la lambda Authorizer
      S3KeyFileLambdaBackEnd: 
        default: Key del archivo con el codigo de la lambda Backend
      CertificateKey: 
        default: Key del certificado SSL
      DomainBack: 
        default: Custom Domain para el API Gateway
      DummyAuthorizer: 
        default: Authorizador Dummy
      DefaultEndpoint: 
        default: Activar endpoint por defecto
      TracingXRay: 
        default: Activar monitoreo con AWS X-Ray
      ApiName: 
        default: Nombre del API Gateway