---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS ECR Repository Transversal
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  Project:
    Type: String
    Default: ito
Resources:
  EcrXRay:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${Project}-${Environment}-x-ray
  EcrBatchTest:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${Project}-${Environment}-test-batch
Outputs:
  EcrXRayUri:
    Value:
      !Sub
        - ${repositoryUri}:latest
        - repositoryUri: !GetAtt EcrXRay.RepositoryUri
    Export:
      Name: !Sub ${Project}-${Environment}-EcrXRayUri