---
AWSTemplateFormatVersion: 2010-09-09
Description: Deploy ECS Service Fargate
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  Project:
    Type: String
    Default: ito
  MicroServiceName:
    Type: String
    Default: dummy
    AllowedPattern: ^([a-z]|[0-9])*$
Resources:
  EcrRegistry1:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${Project}-${Environment}-${MicroServiceName}
Outputs:
  EcrRegistryUri1:
    Value:
      !Sub
        - ${repositoryUri}:latest
        - repositoryUri: !GetAtt EcrRegistry1.RepositoryUri
    Export:
      Name: !Sub ${Project}-${Environment}-${MicroServiceName}-EcrUri