AWSTemplateFormatVersion: 2010-09-09
Description: Deploy de ECS Cluster, Balanceador de Carga, VPC Link y Service Discovery
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - pdn
  Project:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
  EnablePublicIp:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  TypeLoadBalancer:
    Type: String
    Default: network
    AllowedValues:
      - network
      - application
      - gateway
  EnableVpcLink:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  RequireLoadBalancer:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  RequirePrivateDNS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Conditions:  
  isPublic: !Equals [ true, !Ref EnablePublicIp ]
  CreatePrivateDNS: !Equals [ true, !Ref RequirePrivateDNS ]
  CreateLoadBalancer: !Equals [ true, !Ref RequireLoadBalancer ]
  CEnableVpcLink:
    !And
      - !Condition CreateLoadBalancer
      - !Condition isPublic
      - !Equals [ true, !Ref EnableVpcLink]
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Project}-${Environment}-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
  
  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Condition: CreatePrivateDNS
    Properties:
        Name: !Sub ${Project}.${Environment}
        Description: !Sub Private DNS for ${Project} in environment ${Environment}
        Vpc:
          Fn::ImportValue:
            !Sub "${Project}-${Environment}-VpcId"
  
  NetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Condition: CreateLoadBalancer
    Properties:
      Name: !Sub ${Project}-${Environment}-${TypeLoadBalancer}
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: true
      Scheme: !If [ isPublic, internet-facing, internal ]
      Subnets:
        - Fn::ImportValue:
            !Sub "${Project}-${Environment}-SubnetPrivateApp1"
        - Fn::ImportValue:
            !Sub "${Project}-${Environment}-SubnetPrivateApp2"
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Environment}-${TypeLoadBalancer}
      Type: !Ref TypeLoadBalancer
  
  VpcLink:
    Type: 'AWS::ApiGateway::VpcLink'
    Condition: CEnableVpcLink
    Properties:
      Description: !Sub VPC link connects to internal ${Project}-${Environment}-${TypeLoadBalancer}
      Name: !Sub ${Project}-${Environment}-${TypeLoadBalancer}
      TargetArns:
        - !Ref NetworkLoadBalancer

Outputs:
  ClusterName:
    Description: Nombre del Cluster de ECS
    Value: !Ref Cluster
    Export:
      Name: !Sub ${Project}-${Environment}-ClusterName
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
          - Environment
      - Label: 
          default: Datos Balanceador de Carga
        Parameters: 
          - RequireLoadBalancer
          - TypeLoadBalancer
          - EnablePublicIp
          - EnableVpcLink
      - Label: 
          default: Datos DNS Privado
        Parameters: 
          - RequirePrivateDNS
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto
      Environment: 
        default: Nombre del ambiente
      RequireLoadBalancer: 
        default: Requiere Balanceador de Carga
      TypeLoadBalancer: 
        default: Tipo de Balanceador
      EnablePublicIp: 
        default: Requiere IP Pública
      EnableVpcLink: 
        default: Requiere VPC Link