---
AWSTemplateFormatVersion: 2010-09-09
Description: Deploy Dummy ECS Task Definition
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  Project:
    Type: String
    Default: ito
  MicroServiceName:
    Type: String
    Default: dummy
    AllowedPattern: ^([a-z]|[0-9])*$
  Port:
    Type: Number
    Default: 9000
    MinValue: 9000
    MaxValue: 9999
  
  CPU:
    Type: String
    Default: "256"
    AllowedValues:
      - "256"
      - "512"
  RAM:
    Type: String
    Default: "512"
    AllowedValues:
      - "512"
      - "1024"

  DayRetentionLogs:
    Type: String
    Default: 1
    AllowedPattern: ^[1|3|5|7|14|30]?
  
Resources:
  EcrRegistry:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${Project}-${Environment}-${MicroServiceName}

  CloudWatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub /ecs/${Project}-${Environment}-${MicroServiceName}
      RetentionInDays: !Ref DayRetentionLogs
  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Project}-${Environment}-${MicroServiceName}
      Cpu: !Ref CPU
      Memory: !Ref RAM
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::142779088135:role/ExecuteECSRol
      TaskRoleArn: arn:aws:iam::142779088135:role/ExecuteECSRol
      ContainerDefinitions:
        - Name: !Sub ${Project}-${Environment}-xray-daemon
          Image: public.ecr.aws/xray/aws-xray-daemon:latest
          # Cpu: 32
          # MemoryReservation: 256
          PortMappings:
            - ContainerPort: 2000
              Protocol: udp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
        # - Name: cloudwatch-agent
        #   Image: public.ecr.aws/cloudwatch-agent/cloudwatch-agent:latest
        #   Secrets:
        #     - Name: CW_CONFIG_CONTENT
        #       ValueFrom:
        #         Fn::ImportValue:
        #           !Sub ${Project}-${Environment}-XRayAgentConfigArn
        #   LogConfiguration:
        #     LogDriver: awslogs
        #     Options:
        #       awslogs-group: !Ref CloudWatchLogsGroup
        #       awslogs-region: !Ref AWS::Region
        #       awslogs-stream-prefix: ecs
        - Name: !Sub ${Project}-${Environment}-${MicroServiceName}-container
          Environment:
            - Name: PORT
              Value: !Ref Port
          Image: !Sub
            - ${repositoryUri}:latest
            - repositoryUri: !GetAtt EcrRegistry.RepositoryUri
          PortMappings:
            - ContainerPort: !Ref Port
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
  
Outputs:
  ECRImageUriDummy:
    Description: Cluster
    Value:
      !Sub
        - ${repositoryUri}:latest
        - repositoryUri: !GetAtt EcrRegistry.RepositoryUri
    Export:
      Name: Dummy
