---
AWSTemplateFormatVersion: 2010-09-09
Description: Deploy ECS Service - Fargate - With Load Balancer
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  Project:
    Description: Nombre del Proyecto
    Type: String
    Default: ito
  MicroServiceName:
    Description: Nombre del MicroServicio
    Type: String
    Default: dummy
    AllowedPattern: ^([a-z]|[0-9])*$
  Port:
    Description: Puerto que expondrá el MicroServicio
    Type: Number
    Default: 9000
    MinValue: 9000
    MaxValue: 9999
  CPU:
    Description: Cantidad de CPU asignada
    Type: String
    Default: "256"
    AllowedValues:
      - "256"
      - "512"
  RAM:
    Description: Cantidad de RAM asignada
    Type: String
    Default: "512"
    AllowedValues:
      - "512"
      - "1024"
  NumberTask:
    Description: Cantidad de Tareas deseadas
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 2
  EnableDiscoveryService:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  CreateService:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  AgentXRay:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  AgentCloudWatch:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  AgentDataDog:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  EcrEncrytion:
    Type: String
    Default: KMS
    AllowedValues:
      - AES256
      - KMS
  EcrKmsKey:
    Type: String
Conditions:
  requireDiscoveryService: !Equals [ true, !Ref EnableDiscoveryService ]
  isProduction: !Equals [ pdn, !Ref Environment ]
  requireService: !Equals [ true, !Ref CreateService ]
  enablexray: !Equals [ true, !Ref AgentXRay ]
  enablecloudwatch: !Equals [ true, !Ref AgentCloudWatch ]
  enabledatadog: !Equals [ true, !Ref AgentDataDog ]
  isEcrKmsKeyProvided: !Not [ !Equals [ !Ref EcrKmsKey, "" ] ]
Resources:
  EcrRegistry:
    Type: AWS::ECR::Repository
    Properties: 
      EmptyOnDelete: true
      EncryptionConfiguration:
        EncryptionType: !Ref EcrEncrytion
        KmsKey: !If [ isEcrKmsKeyProvided, !Ref EcrKmsKey, !Ref AWS::NoValue ]
      ImageScanningConfiguration:
        ScanOnPush: false
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub ${Project}-${Environment}-${MicroServiceName}

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Condition: requireDiscoveryService
    Properties: 
      Description: !Sub Discovery Service for ${MicroServiceName} app
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: !Ref MicroServiceName
      NamespaceId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-NameSpaceCloudMapId
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: requireService
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckTimeoutSeconds: 2
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      TargetType: ip
      Name: !Sub "${Project}-${Environment}-${MicroServiceName}"
      Port: !Ref Port
      Protocol: TCP
      Tags:
        - Key: Name
          Value: !Sub "${Project}-${Environment}-${MicroServiceName}"
      VpcId:
        Fn::ImportValue:
          !Sub "${Project}-${Environment}-VpcId"

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Condition: requireService
    Properties:
      LogGroupName: !Sub /ecs/${Project}-${Environment}-${MicroServiceName}
      RetentionInDays: 1
  
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: requireService
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-NetWorkLoadBalancerArn
      Port: !Ref Port
      Protocol: TCP

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: requireService
    Properties:
      Family: !Sub "${Project}-${Environment}-${MicroServiceName}"
      Cpu: !Ref CPU
      Memory: !Ref RAM
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub "${Project}-${Environment}-ECSTaskExecutionRoleArn"
      TaskRoleArn:
        Fn::ImportValue:
          !Sub "${Project}-${Environment}-ECSTaskRoleArn"
      ContainerDefinitions:
        - !If
          - enablexray
          - Name: !Sub ${Project}-${Environment}-xray-daemon
            Image: public.ecr.aws/xray/aws-xray-daemon@sha256:8d74426fd86f830c6793180dcefcba76ba8258eaf2deba68a612944d1845030d
              # Fn::ImportValue:
              #   !Sub ${Project}-${Environment}-EcrXRayUri
            # Cpu: 32
            # MemoryReservation: 256
            Essential: false
            PortMappings:
              - ContainerPort: 2000
                Protocol: udp
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref CloudWatchLogsGroup
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: ecs
          - !Ref AWS::NoValue
        - !If
          - enablecloudwatch
          - Name: cloudwatch-agent
            Image: public.ecr.aws/cloudwatch-agent/cloudwatch-agent:latest@sha256:f3427f46e4a7de9c2e6009ab7955924ed0454e6e021cff729ff7f9d24f13555b
            Essential: false
            Secrets:
              - Name: CW_CONFIG_CONTENT
                ValueFrom:
                  Fn::ImportValue:
                    !Sub ${Project}-${Environment}-XRayAgentConfigArn
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref CloudWatchLogsGroup
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: ecs
          - !Ref AWS::NoValue
        - Name: !Sub "${Project}-${Environment}-${MicroServiceName}-container"
          # EnvironmentFiles:
          #   - Type: s3
          #     Value: arn:aws:s3:::kiire-s3-ecs-env-files-dev/dev/kiire-ecs-env-file-dev.env
          Environment:
            - Name: PORT
              Value: !Ref Port
            - Name: TableName
              Value: Country
          # Secrets:
          #   - Name: stage
          #     ValueFrom: arn:aws:ssm:us-east-1:142779088135:parameter/STAGE
          #   - Name: DB_PASSWORD
          #     ValueFrom: arn:aws:ssm:us-east-1:142779088135:parameter/DB_PASSWORD_DEV
          #   - Name: DB_URL
          #     ValueFrom: arn:aws:ssm:us-east-1:142779088135:parameter/DB_URL_DEV
          #   - Name: DB_USERNAME
          #     ValueFrom: arn:aws:ssm:us-east-1:142779088135:parameter/DB_USERNAME_DEV
          Image:
            !Sub
              - ${repositoryUri}:latest
              - repositoryUri: !GetAtt EcrRegistry.RepositoryUri
          Essential: true
          # HealthCheck:
          #   Command:
          #     - CMD-SHELL
          #     - !Sub curl -f http://localhost:${Port}/api/dummy || exit 1
          #   Interval: 30
          #   Timeout: 5
          #   Retries: 3
          #   StartPeriod: 150
          PortMappings:
            - ContainerPort: !Ref Port
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Condition: requireService
    DependsOn:
      - Listener
    Properties:
      ServiceName: !Sub ${Project}-${Environment}-${MicroServiceName}
      Cluster:
        Fn::ImportValue:
          !Sub "${Project}-${Environment}-ClusterName"
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !Ref NumberTask
      HealthCheckGracePeriodSeconds: 10
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub "${Project}-${Environment}-SecurityGroupBackEnd"
          Subnets:
            - Fn::ImportValue:
                !Sub ${Project}-${Environment}-SrvSub1
            - !If
                - isProduction
                - Fn::ImportValue:
                    !Sub ${Project}-${Environment}-SrvSub2
                - !Ref AWS::NoValue
      ServiceRegistries:
        !If
          - requireDiscoveryService
          - - RegistryArn: !GetAtt DiscoveryService.Arn
          - !Ref AWS::NoValue
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Sub "${Project}-${Environment}-${MicroServiceName}-container"
          ContainerPort: !Ref Port
          TargetGroupArn: !Ref TargetGroup
Outputs:
  ServiceName:
    Condition: requireService
    Description: Nombre del Servicio de ECS
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub ${Project}-${Environment}-${MicroServiceName}-ECSService
  EcrRegistryRepositoryUri:
    Description: Url de la imagen de ECR
    Value:
      !Sub
        - ${repositoryUri}:latest
        - repositoryUri: !GetAtt EcrRegistry.RepositoryUri
    Export:
      Name: !Sub ${Project}-${Environment}-${MicroServiceName}-RepositoryUri
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
          - Environment
      - Label: 
          default: Información del Servicio
        Parameters: 
          - CreateService
          - MicroServiceName
          - Port
          - CPU
          - RAM
          - NumberTask
      - Label:
          default: Agentes
        Parameters:
          - AgentXRay
          - AgentCloudWatch
          - AgentDataDog
      - Label:
          default: Cifrado de Imagen Docker
        Parameters:
          - EcrEncrytion
          - EcrKmsKey
      - Label: 
          default: Componentes Adicionales
        Parameters: 
          - EnableDiscoveryService
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto
      Environment: 
        default: Nombre del Ambiente
      CreateService:
        default: Crear Recursos del Servicio?
      MicroServiceName:
        default: Nombre del servicio
      Port:
        default: Número del puerto
      CPU:
        default: Cantidad Unidades de CPU
      RAM:
        default: Cantidad de RAM
      NumberTask:
        default: Número de Tareas
      EnableDiscoveryService:
        default: Habilitar DNS Privado
      AgentXRay:
        default: Activar Agente XRay
      AgentCloudWatch:
        default: Activar Agente CloudWatch
      AgentDataDog:
        default: Activar Agente DataDog
      EcrEncrytion:
        default: Tipo de Cifrado
      EcrKmsKey:
        default: KMS Key
