AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Buckets assets, pinpoint and formatos
Parameters:
  # KMSS3KeyId:
  #   Description: Id del Key de KMS para S3
  #   Type: String
  #   Default: AWS-S3-key
  Project:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
Resources:
  BucketDeployments:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${Project}-${AWS::AccountId}-lambda-deployments
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - BucketKeyEnabled: true
      #       ServerSideEncryptionByDefault:
      #         KMSMasterKeyID:
      #           Fn::Sub:
      #             - arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSS3KeyId}
      #             - KMSS3KeyId:
      #                 Ref: KMSS3KeyId
      #         SSEAlgorithm: aws:kms
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Descripcion
          Value: Almacenar los artefactos generados al compilar las funciones lambdas
  BucketArchetypes:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${Project}-${AWS::AccountId}-archetypes
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - BucketKeyEnabled: true
      #       ServerSideEncryptionByDefault:
      #         KMSMasterKeyID:
      #           Fn::Sub:
      #             - arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSS3KeyId}
      #             - KMSS3KeyId:
      #                 Ref: KMSS3KeyId
      #         SSEAlgorithm: aws:kms
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Descripcion
          Value: Almacenar los arquetipos del proyecto
  BucketPipelinesArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${Project}-${AWS::AccountId}-pipeline-artifacts
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - BucketKeyEnabled: true
      #       ServerSideEncryptionByDefault:
      #         KMSMasterKeyID:
      #           Fn::Sub:
      #             - arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSS3KeyId}
      #             - KMSS3KeyId:
      #                 Ref: KMSS3KeyId
      #         SSEAlgorithm: aws:kms
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Descripcion
          Value: Almacenar los artefactos generados en los pipelines
Outputs:
  BucketDeploymentsName:
    Description: Nombre del bucket para guardar los deployments de proyectos
    Value: !Ref BucketDeployments
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketDeploymentsName
  BucketDeploymentsArn:
    Description: Arn del bucket para guardar los deployments de proyectos
    Value: !GetAtt BucketDeployments.Arn
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketDeploymentsArn
  BucketArchetypesName:
    Description: Nombre del bucket para guardar los arquetipos del proyecto
    Value: !Ref BucketArchetypes
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketArchetypesName
  BucketArchetypesArn:
    Description: Arn del bucket para guardar los arquetipos del proyecto
    Value: !GetAtt BucketArchetypes.Arn
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketArchetypesArn
  BucketPipelinesArtifactsName:
    Description: Nombre del bucket para guardar los artefactos generados en los pipelines
    Value: !Ref BucketPipelinesArtifacts
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketPipelinesArtifactsName
  BucketPipelinesArtifactsArn:
    Description: Arn del bucket para guardar los artefactos generados en los pipelines
    Value: !GetAtt BucketPipelinesArtifacts.Arn
    Export:
      Name: !Sub ${Project}-${AWS::AccountId}-BucketPipelinesArtifactsArn
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto