AWSTemplateFormatVersion: 2010-09-09
Description: "Creacion de VPC"

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: "A friendly environment name that will be used for namespacing all resources (valid options are dev, qa or production)"
    AllowedValues: [ dev, qa, prod ]
  Project:
    Type: String
    Default: ito
    AllowedPattern: ^([a-z]|[0-9])*$
Resources:
## VPC Endpoints ##
  XRay:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.xray
      VpcId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-VpcId
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SrvSub1
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SecurityGroupVpcEndPoints
  
  CloudWatchLogs:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-VpcId
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SrvSub1
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SecurityGroupVpcEndPoints
  
  EcrApi:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-VpcId
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SrvSub1
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SecurityGroupVpcEndPoints
  
  EcrDkr:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-VpcId
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SrvSub1
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-SecurityGroupVpcEndPoints

  S3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: false
      VpcEndpointType: Gateway
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId:
        Fn::ImportValue:
          !Sub ${Project}-${Environment}-VpcId
      RouteTableIds:
        - Fn::ImportValue:
            !Sub ${Project}-${Environment}-PrivateRouteTable

Outputs:
  VPCEXRay:
    Description: VPC Endpoint X-Ray
    Value: !Ref XRay
    Export:
      Name: !Sub ${Project}-${Environment}-VPCE-X-Ray
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Datos del Proyecto
        Parameters: 
          - Project
          - Environment
    ParameterLabels: 
      Project: 
        default: Nombre del Proyecto
      Environment: 
        default: Nombre del Ambiente