name: Subir archivos a S3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Reemplaza con tu región
      - name: Subir archivos a S3
        uses: aws-actions/aws-s3@v2
        with:
          bucket: ito-437950194672-cloudformation
          region: us-east-1
          files: '/**'