name: Subir archivos a S3

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Reemplaza con tu región
      - name: Upload files to S3 bucket
        uses: EndBug/add-and-commit@v9
        with:
          message: Add files to commit
        run: |
          aws s3 cp . s3://ito-437950194672-cloudformation