AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudFront origin security with Cognito, AWS WAF and AWS Secrets Manager

Parameters:
  HeaderName:
    Default: X-Origin-Verify
    Description: Header name for secret string.
    Type: String
Resources:
  # generate random X-Origin-Verify header value using Secrets Manager
  OriginVerifyHeader:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "Origin Custom Header value for CloudFront"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"HEADERVALUE": "RandomHeader"}'
        GenerateStringKey: "HEADERVALUE"
        ExcludePunctuation: true

  RotateFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OriginSecretRotateFunction
      Action: lambda:InvokeFunction
      Principal: "secretsmanager.amazonaws.com"

  OriginVerifyRotateSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotationLambdaARN: !GetAtt OriginSecretRotateFunction.Arn
      RotationRules:
        # AutomaticallyAfterDays: 7
        ScheduleExpression: rate(4 hours)
      SecretId: !Ref OriginVerifyHeader

  # rotate header using Secrets Manager and it referrs to RotationRules
  OriginSecretRotateFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Serets Manager Rotation Lambda
      Handler: index.handler
      Runtime: python3.9
      # Layers:
      #   - !Ref PythonRequestsLayer
      #VpcConfig: # For accessing RDS instance
      #  SecurityGroupIds:
      #    - !Ref LambdaSecurityGroup
      #  SubnetIds:
      #    - !Ref WAprivateLambdaSubnet1
      Environment:
        Variables:
          HEADERNAME: !Ref HeaderName
          STACKNAME: !Ref AWS::StackName
          AWSREGION: !Ref AWS::Region
      Role: !GetAtt OriginSecretRotateExecutionRole.Arn
      Timeout: 60
      Code:
        S3Bucket: ito-437950194672-lambda-deployments
        S3Key: secrets-manager-rotation.zip

  OriginSecretRotateExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OriginVerifyRotatePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*OriginSecretRotateFunction*"
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:UpdateSecretVersionStage
                Resource: !Ref OriginVerifyHeader
              - Effect: Allow
                Action:
                  - secretsmanager:GetRandomPassword
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudfront:UpdateDistribution
                Resource: "*"
              - Effect: Allow
                Action:
                  - wafv2:*
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  OriginSecretRotateFunction:
    Value: !Sub https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${OriginSecretRotateFunction}
    Description: Secrets Manager Rotation Lambda Function
  OriginVerifyHeaderName:
    Description: Origin Header Name in CloudFront
    Value: !Ref HeaderName
  OriginVerifyHeader:
    Description: Origin Header for Origin Validation
    Value: !Sub https://console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#/secret?name=${OriginVerifyHeader}
